name: Evaluate catalogs
on:
  pull_request:
    types: [ opened, review_requested, ready_for_review, reopened, synchronize ]
    branches:
      - main
    paths:
      - 'catalogs/**'
      - 'markdown/catalogs/**'
jobs:
  release:
    name: Evaluate catalog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Sanity check
        run: |
          make assemble-catalog
          make regenerate-catalog
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply sanity changes