name: Catalog check
on:
  pull_request:
    branches:
      - main
    paths:
      - 'catalogs/**'
      - 'markdown/catalogs/**'

jobs:
  auto-update:
    name: Assemble catalog content
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Check
        id: check
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@feat/replace-check-only
        with:
          markdown_path: "markdown/catalogs"
          oscal_model: "catalog"
          file_pattern: "*.json markdown/*"
          commit_message: "test"
          dry_run: "true"
      - name: Fail
        if: ${{ steps.check.outputs.changes == "true" }}
        uses: actions/github-script@v7
        with:
          script: |
              core.setFailed('Changes detected. Manual intervention required.')
    
