name: Catalog updates
on:
  push:
    branches:
      - main
    paths:
      - 'catalogs/**'
      - 'markdown/catalogs/**'

jobs:
  auto-update:
    name: Assemble catalog content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Automatically update content on push
        run: make assemble-catalogs
      - name: commit and push changes
        id: commit
        env:
          ACTOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        run: bash ./vendor/scripts/update-push.sh -c "automated changes - assemble" -a "$ACTOR" "catalogs/*"
  
  auto-update-profiles:
    name: Regenerate profile content
    runs-on: ubuntu-latest
    needs: auto-update
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Regenerate profiles
        run: make regenerate-profiles
      - name: Update and PR
        env:
          ACTOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./vendor/scripts/update.sh -c "Sync OSCAL profiles" -a "$ACTOR" "markdown/*
