name: Catalog updates
on:
  pull_request:
    branches:
      - main
    paths:
      - 'catalogs/**'
      - 'markdown/catalogs/**'

jobs:
  auto-update:
    name: Assemble catalog content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Assemble
        id: assemble
        uses: jpower432/trestle-bot@PSCE-194
        with:
          markdown_path: "markdown/catalogs"
          oscal_model: "catalog"
          file_pattern: "*.json,markdown/*"
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    