name: Component definition updates
on:
  pull_request:
    branches:
      - main
    paths:
      - 'component-definitions/**'
      - 'markdown/components/**'

jobs:
  auto-update:
    name: Assemble cd content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Assemble
        id: assemble
        uses: jpower432/trestle-bot/actions/autosync@PSCE-249
        with:
          markdown_path: "markdown/components"
          oscal_model: "compdef"
          file_pattern: "*.json,markdown/*"
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    