name: Component definition updates
on:
  push:
    branches:
      - main
    paths:
      - 'component-definitions/**'
      - 'markdown/components/**'

jobs:
  auto-update:
    name: Assemble compdef content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Automatically update content on push
        run: make assemble-cd
      - name: commit and push changes
        id: commit
        run: bash ./vendor/scripts/update-push.sh -c "automated changes - assemble" "component-definitions/*"
        
  auto-update-ssp:
    name: Regenerate ssp content
    runs-on: ubuntu-latest
    needs: auto-update
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Regenerate FedRAMP SSP
        run: make generate-fedramp-ssp
      - name: Regenerate custom SSP
        run: make generate-custom-ssp
      - name: Assemble ssps
        run: make assemble-ssps
      - name: Update and PR
        run: bash ./vendor/scripts/update.sh -c "Sync OSCAL SSPs" "markdown/* system-security-plans/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}