name: Component Definitions Create
on:
  workflow_dispatch:
   inputs:
      import_name:
        required: true
        description: Name of profile in trestle workspace to be imported
      output:
        required: true
        description: Name of the component definition to create
      component_name:
        required: true
        description: Name of the component in the generated component definition
      component_description:
        required: true
        description: Description of the component in the generated component definition
     

jobs:
  create-component:
    name: Create component definition
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Generate and PR new component definition
        id: generate-cd
        uses: jpower432/trestle-bot/actions/create-cd@PSCE-289
        with:
          profile_name: ${{ github.event.inputs.import_name }}
          component_definition_name: ${{ github.event.inputs.output }}
          component_title: ${{ github.event.inputs.component_name }}
          component_description: ${{ github.event.inputs.component_description }}
          markdown_path: "markdown/components"
          branch: "component-create-${{ github.run_id }}"
          target_branch: "main"
          file_pattern: "*.json,markdown/*"
          commit_user_name: "trestle-bot[bot]"
          commit_user_email: "136850459+trestle-bot[bot]@users.noreply.github.com"
          commit_message: "adds component  ${{ github.event.inputs.component_name }} in ${{ github.event.inputs.output }}"
          pull_request_title: "Add component ${{ github.event.inputs.component_name }} to ${{ github.event.inputs.output }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
