name: Profile updates
on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'markdown/profiles/**'

jobs:
  auto-update:
    name: Assemble profile content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Automatically update content on push
        run: make assemble-profiles
      - name: commit and push changes
        id: commit
        env:
          ACTOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        run: bash ./vendor/scripts/update-push.sh -c "automated changes - assemble" -a "ACTOR" "profiles/*"

  auto-update-profiles:
    name: Regenerate downstream content
    runs-on: ubuntu-latest
    needs: auto-update
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Regenerate component-definitions
        run: make regenerate-profiles
      - name: Update and PR
        env:
          ACTOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./vendor/scripts/update.sh -c "Sync OSCAL Profiles" -a "ACTOR" "markdown/*"

  auto-update-cd:
    name: Regenerate compdef content
    runs-on: ubuntu-latest
    needs: auto-update
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Regenerate component-definitions
        run: make regenerate-cd
      - name: Update and PR
        env:
          ACTOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./vendor/scripts/update.sh -c "Sync OSCAL CD" -a "ACTOR" "markdown/*"
  
  auto-update-ssp:
    name: Regenerate ssp content
    runs-on: ubuntu-latest
    needs: auto-update
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Regenerate FedRAMP SSP
        run: make generate-fedramp-ssp
      - name: Regenerate custom SSP
        run: make generate-custom-ssp
      - name: Update and PR
        env:
          ACTOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./vendor/scripts/update.sh -c "Sync OSCAL SSPs" -a "ACTOR" "markdown/*"