name: Regenerate ssps
on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'component-definitions/**'

jobs:
  auto-update-profiles:
    name: Regenerate ssp content
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Regenerate ssp
        id: regenerate
        uses: jpower432/trestle-bot@feat/add-regenerate
        with:
          markdown_path: "markdown/system-security-plans"
          oscal_model: "ssp"
          file_pattern: "markdown/*"
          branch: "autoupdate-${{ github.run_id }}"
          skip_assemble: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}