name: Regenerate profiles
on:
  push:
    branches:
      - main
    paths:
      - 'catalogs/**'
      - 'profiles/**'

jobs:
  auto-update-profiles:
    name: Regenerate profile content
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Regenerate profiles
        id: regenerate
        uses: jpower432/trestle-bot@feat/add-regenerate
        with:
          markdown_path: "markdown/profiles"
          oscal_model: "profile"
          file_pattern: "markdown/*"
          branch: "autoupdate-${{ env.GITHUB_RUN_ID }}"
          skip_assemble: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}