name: SSP updates
on:
  push:
    branches:
      - main
    paths:
      - 'system-security-plans/**'
      - 'markdown/system-security-plans/**'
jobs:
  auto-update:
    name: Assemble ssp content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Assemble
        id: assemble
        uses: jpower432/trestle-bot@feat/add-regenerate
        with:
          markdown_path: "markdown/system-security-plans"
          assemble_model: "ssp"
          file_pattern: "*.json markdown/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  